### ISSUE TITLE
Error when compiling the master branch code

### ISSUE THREAD

**Issue by wanglei837** [Mellanox/nccl-rdma-sharp-plugins#139]
My environment:
- cuda: 12.2
- sharp + verbs: the version from ofed 23.07
It seems like the difference between allgather & allreduce, and the details are in the image below.
![20240104-160336](https://github.com/Mellanox/nccl-rdma-sharp-plugins/assets/135590943/81638130-c907-41c1-85e4-977d24de1386)

**Comment by antony-frolov** [comment]
Got the same error

**Comment by dmitrygx** [comment]
@wanglei837 it should not be a problem with SHARP which comes with HPC-X 2.17.1, but doesn't work with previous verions.

@bureddy I think it would be great to add a check in configure.ac for SHARP's reduce-scatter symbols and not use it in the plugin if they are not declared to make sure we could support the plugin with old version of SHARP. wdyt?
