### ISSUE TITLE
question about at least version

### ISSUE THREAD

**Issue by likueimo** [Mellanox/nccl-rdma-sharp-plugins#21]
According readme
## Requirements

* MOFED
* CUDA
* SHARP
* NCCL
* GPUDirectRDMA plugin

I am curious about this repo requires at least version.
Our HPC cluster install with 
- MLNX_OFED 4.4 
- CUDA 9.0/9.2/10.0/10.1/10.2
- Sharp 1.7.1
- NCCL 2.4/2.5. 
- GPUDirectRDMA plugin (https://github.com/Mellanox/nv_peer_memory)

Is this suitable condition for this plugins? 
Or which version of this component already tested? Many Thanks!

**Comment by Sergei-Lebedev** [comment]
Hi @likueimo 
the plugin requires following software/hardware
1) NCCL 2.6 (hasn't been released yet but you can try this branch https://github.com/NVIDIA/nccl/tree/v2.6)
2) ConnectX 6 HCA
2) SHARP 1.7 should work but SHARP 2 is needed to get best performance
3) Any version of CUDA and nv_peer_mem should work

**Comment by likueimo** [comment]
> Hi @likueimo
> the plugin requires following software/hardware
> 
> 1. NCCL 2.6 (hasn't been released yet but you can try this branch https://github.com/NVIDIA/nccl/tree/v2.6)
> 2. ConnectX 6 HCA
> 3. SHARP 1.7 should work but SHARP 2 is needed to get best performance
> 4. Any version of CUDA and nv_peer_mem should work

HI @Sergei-Lebedev 
Our HCA is ConnectX 5, 
so this plugin might not be suitable for our HPC cluster.
Thanks for your quick reply !
